TEMPLATEROOT = ..

# compilation flags for gdb

CFLAGS  = -Os -g3
ASFLAGS = -g3

# object files

OBJS= stupid_delay.o main.o $(STARTUP)

# include common make file

include $(TEMPLATEROOT)/Makefile.common


