TEMPLATEROOT = ..

# compilation flags for gdb

CFLAGS  = -O0 -g3
ASFLAGS = -g3

# object files

OBJS= stupid_delay.o main.o nm120.o i2c.o spi.o $(STARTUP)

# include common make file

include $(TEMPLATEROOT)/Makefile.common


